### ISSUE TITLE
passwordreset template url

### ISSUE THREAD

**Issue by Milanvdm** [deitch/activator#20]
````
<%= request.protocol %>://<%= request.headers.host %>/reset/my/password?code=<%= code %>&email=<%= email %>&user=<%= id %>
````

This is the sent url using your passwordreset.txt example.
But this url doesn't contain the needed req.param('password').

Also in the example and test code, you add the password through json. So I don't see how we can send a correct url to the user with the provided attributes we can add in the mail template.

**Comment by deitch** [comment]
> But this url doesn't contain the needed `req.param('password')`

I don't understand the issue. Can you explain it?
The flow is:

1. User hits reset password
2. User receives email with a link to click, which contains their one-time token (as above)
3. Link goes to a page wherein they enter the new password
4. User submits, which sends both the new password and the token, thus changing the password

Which part doesn't work?

> Also in the example and test code, you add the password through json. 
> So I don't see how we can send a correct url to the user with the provided attributes we can add in the mail template.

Same as above. The new password is submitted as a `POST` from a new page; we never want to send a password via `GET` params. The code is stuck in the params just to ease populating the page; we could have put it in the email, and had the user manually enter it.

**Comment by Milanvdm** [comment]
I was under the impression for some reason that activator also generated a new password.
My bad.

**Comment by deitch** [comment]
I guess in some ways it does. The one-time code could be treated as a temporary new password. The only difference is that it is time-limited, and the old one continues to be valid.

What would a different workflow be like?

**Comment by Milanvdm** [comment]
A different flow will be that the generated link also contains the new password.
So the activator could just generate this new password itself and pass it through the email.
Because on that generated link, it could save the new password using the userModel.save method or something similar.

**Comment by deitch** [comment]
Let's see if we can make this an option.

The way it works now, there are 3 relevant fields in the user model:

* `password`: this stores the actual user password (hashed however - that is up to your model implementation)
* `password_reset_code`: this is the one-time code used to validate a reset
* `password_reset_time`: how long the code is valid for. The developer can configure this, but it defaults to 60 minutes.

So the way it works is:

1. User hits password reset
2. System creates a random reset code (actually a sha1 hash of the user email and timestamp and some random stuff, etc.)
3. System saves the reset code and the reset expiry in the model
4. System sends an email to the user with the code and a link
5. User clicks link, gets a page
6. User enters new password and hits send
7. System validates the code matches, the expiry is not past, and saves the new password
8. System changes expiry to 0 (i.e. not applicable) and the reset code to "X" (so no one else can reset it)

The reason the system works this way is so that someone else cannot reset my password without me; they can only set it up for reset, by creating the code; I can still log in with my old password.

* The code is sent to my email
* The code is independent of the password
* The code expires after a fixed time (default 1 hour)

If we actually changed the password, then anyone could force my password to change. They might not get the new one, but they could still prevent me from logging in until I check my email.

Unless we can find a way around it, I would be reluctant to have it actually change the password as it would be a vector of attack, a sort of denial of service on an per-user basis.

What might be interesting is if we kept the code, but instead of the link bringing you a place to enter your new password, it brought you somewhere that auto-generated a new password...
