### ISSUE TITLE
EJSONPARSE on Package json file

### ISSUE THREAD

**Issue by molinto** [deitch/activator#26]
**npm install activator** or **npm install activator --save**

Fails here too:
http://package-json-validator.com/

info it worked if it ends with ok
verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'activator' ]
info using npm@1.3.10
info using node@v0.10.25
error Failed to parse json
error Unexpected token }
error File: /website/package.json
error Failed to parse package.json data.
error package.json must be actual JSON, not just JavaScript.
error
error This is not a bug in npm.
error Tell the package author to fix their package.json file. JSON.parse
error System Linux 3.13.0-55-generic
error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "activator"
error cwd /website
error node -v v0.10.25
error npm -v 1.3.10
error file /website/package.json
error code EJSONPARSE
verbose exit [ 1, true ]

**Comment by deitch** [comment]
I have no issues with it, but I see you are running a pretty old version of `npm`, 1.3.10. Have you tried it with 2.x?

**Comment by molinto** [comment]
Hi, yep, just tried on v2.13. Still fails.

Your engines part of package is an array & should be an object to failing package.json validation.
See here for details: https://docs.npmjs.com/files/package.json#engines

I've submitted a pull req.

Sharry

**Comment by deitch** [comment]
Yeah, I know. I think `engines` used to be an array. It actually makes a lot more sense as an object (which is why it is).

Very strange that it fails on yours but runs on mine... but either way, it should be fixed.

OK, closing this issue and will use your pull (or just fix it locally, since I did it when you raised it but didn't save or push....)
