### ISSUE TITLE
Function for templates

### ISSUE THREAD

**Issue by miqmago** [deitch/activator#49]
I'm trying to rewrite how activator fetches templates, in order to be able to pass a function to templates as my whole app is localized and uses mongodb to store texts. I've been thinking if maybe it could be possible that activator fetch the templates with a user function, so I was thinking to write this lines of code in `mailcomposer.js` line 53:

``` js
        if (found) {
            callback(null,found);
        } else if (typeof path === 'function') {
            mails[type][lang] = mails[type][lang] || {};
            async.parallel([
                function (cb) {
                    var promise = path(type+'_text',lang,cb);
                    if (typeof promise.then === 'function') {
                        promise.then(function (result1) {
                            cb(null, result1);
                        }, function () {
                            cb(null, '');
                        });
                    }
                },
                function (cb) {
                    var promise = path(type+'_html',lang,cb);
                    if (typeof promise.then === 'function') {
                        promise.then(function (result1) {
                            cb(null, result1);
                        }, function () {
                            cb(null, '');
                        });
                    }
                }
            ], function (err, results) {
                var dataText = results[0];
                var dataHtml = results[1];

                if (dataText) {
                    dataText = dataText.replace(/\r\n/g,'\n');
                    dataText = dataText.match(/^([^\n]*)\n[^\n]*\n((.|\n)*)/m);
                    mails[type][lang]['text'] = {
                        subject: _.template(dataText[1]),
                        content: _.template(dataText[2]),
                        expired: now + EXPIRY*60*1000,
                    };
                } else {
                    mails[type][lang]['text'] = {
                        notfound: true,
                        expired : now + EXPIRY*60*1000
                    };
                }
                if (dataHtml) {
                    dataHtml = dataHtml.replace(/\r\n/g,'\n');
                    dataHtml = dataHtml.match(/^([^\n]*)\n[^\n]*\n((.|\n)*)/m);
                    mails[type][lang]['html'] = {
                        subject: _.template(dataHtml[1]),
                        content: _.template(dataHtml[2]),
                        expired: now + EXPIRY*60*1000,
                    };
                } else {
                    mails[type][lang]['html'] = {
                        notfound: true,
                        expired : now + EXPIRY*60*1000
                    };
                }
                callback();
            });
        } else {
            fs.readdir(path,function (err,files) {
```

In that way one could facilitate a function that has the following signatures:

``` js
templates: function (key, lang, callback) {
    callback(null, 'Text for key and lang');
}
```

or 

``` js
templates: function (key, lang) {
    var promise = fetch(key, lang);
    return promise;
}
```

If it sounds good I can make a pull request but what I'm not sure if I will be able to write tests for it, I've been reading them and I'm not really understanding them at all.

**Comment by deitch** [comment]
I love i18n - you can tell from the fact that the template files support i18n with the filename extensions - I wrote a very early i18n JS library many years ago. Lots has surpassed it since, but take pride in being one of the very first. :-)

So, let's see if I get this. Right now, templates are pulled from the filesystem. You pass `activator.init()` the option `templates` , whose value is an absolute path to templates.

You are suggesting, let's replace that path with a driver that knows how to fetch templates. If the path is a function, use that to retrieve the correct template. You pass it the name of the template and the locale, it returns the text to use? And then files become just one more driver (i.e. a different function)?

**Comment by miqmago** [comment]
Yeah! That's it :) I'll test this code next days. I can come back with more info then, just wanted to know your opinion, and to let you know that I'm not sure if will be able to write tests, but if it works then I could do pull request.

In fact what I'm suggesting is that if the path is a function, use it to retrieve the texts in a promised or node-callback style. If it is a string, then use it as an absolute path (the same way it was before).

As I've seen you don't use the `path` variable until you `get` them (in `compile` function):

```
activator.init({ templates: function () {}, ... });
    --> smtp(transport, templates, ...) (mailer.js)
        --> mailcomposer.init(templates, ...) (mailcomposer.js)
            --> path = p || PATH;
```

So path is directly `templates` init property. In this way, if it is a string, then is what is now. If it is a function, it is a driver.

**Comment by deitch** [comment]
Definitely on board. I like the idea of abstracting it out, and would appreciate a PR. A few comments:

1. Tests really are important. If I have to choose, I lean more towards integration than unit, but at least something. If you get stuck, put in the comments here and we can collaborate on it.
2. I wouldn't mind having it be a driver no matter what; make the files just another driver. 

For the last point, rather than having `templates` property sometimes be a string and sometimes a function, I think it would be cleaner if it is *always* a function. 

But we would provide a convenience function to generate it for files:

````javascript
// for custom drivers
var templateDriver = function(){/*...*/};
activator.init({templates: templateDriver});

// for files
var templateDriver = activator.templates.file('/path/to/templates/');
activator.init({templates: templateDriver});
````

We _could_ have a shortcut format wherein if `typeof(templates) === 'string'` then all `activator.templates.file(templatesVar)`, but it restricts us going forward. What if we want to use a URL? SQL address? Email address? Something else? Most are unlikely, but is `activator.init({templates: '/path/to/templates'})` **really** harder than `activator.init({templates: activator.templates.file('/path/to/templates')})`? I don't think so.

We would need to bump major version number because of backwards incompatibility but I am OK with that. 

As for where we use `templates`, you are correct. It is passed all the way through, as is, until `mailcomposer.js`, where it is used.

Next steps on this: 

* driver for files
* driver test for files
* custom driver interface
* custom driver interface test

**Comment by miqmago** [comment]
I've pushed an early version to my fork, you can take a look here. This is tremendous difficult to make both functionalities compatible with the same function, but I think this is a first approach. Please if you can take a look that would be really great.

https://github.com/miqmago/activator

**Comment by deitch** [comment]
@miqmago I would be happy to take a look. How about we start with a Pull Request? Rather than digging through the code, a PR will highlight automatically all of the changes, and make it easy to do code reviews, and then finally merge.


Just go ahead and open a PR into `deitch/activator:master` from `miqmago/activator:master` and let's work it through from there?
