### ISSUE TITLE
authentication vs authorization

### ISSUE THREAD

**Issue by miqmago** [deitch/activator#54]
Don't know which one is wrong: 

https://github.com/deitch/activator/blob/master/README.md#templates-format Line 533 `authorization`

https://github.com/deitch/activator/blob/master/lib/activator.js#L69 `authentication`

**Comment by deitch** [comment]
Well, if that isn't a sloppy mistake! Nice catch.

Clearly, it should be `authentication`, since the code authenticates who you are, it does not authorize you to do anything. In any case, wouldn't want to break anything working without good reason. 

Fixing now, closing in favour of immediate PR. Thanks for finding.

**Comment by miqmago** [comment]
I've seen that anyway `code` can be used in any case (they are the same value...)

So I understand that this will be fixed in `README.md` not in code (as you said, it could break projects using as it is now...)

**Comment by deitch** [comment]
Yep. Just merged and `npm publish`ed. Thanks again.
